### ISSUE TITLE
etcd tls

### ISSUE THREAD

**Issue by jhrv** [nais/naisible#12]
Generate and use client certificates for:
- cluster peer-communication
- flannel
- apiserver

**Comment by Kyrremann** [comment]
@jhrv er dette noe vi kommer til å gjøre?

**Comment by jhrv** [comment]
ja, asap egentlig :)

**Comment by Kyrremann** [comment]
Ok, kanskje få lagd en Trello-sak på det? For tror ikke folk følger så veldig mye med på issues. Er jo mange andre saker oms er tatt i mellomtiden :p
